name: Django CI Pipeline

on:
  push:
    branches: [feature/backend-setup]
  pull_request:
    branches: [main, feature/backend-setup]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13  # PostgreSQL 버전 지정
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: asd123
          POSTGRES_DB: workwise_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies from requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install coverage

      - name: Run Django tests with coverage
        env:
          DJANGO_SETTINGS_MODULE: backend.settings
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: asd123
          POSTGRES_DB: workwise_db
          DATABASE_HOST: localhost
          DATABASE_PORT: 5432
        run: |
          cd backend
          coverage run manage.py test
          coverage report

          
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
  
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/workwise-backend:latest -f Dockerfile .
  
      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/workwise-backend:latest